- hosts: localhost
  vars:
    vm_name: "{{ vm_name }}"  # VM name, dynamically passed from AAP Job Template
    template_name: "{{ catalog_name }}"  # The catalog template name
    namespace: "openshift"  # Namespace where the catalog template is stored
    target_namespace: "aap-vm-auto-provision-test"  # Target namespace for the VM
  tasks:
    - name: Fetch the VirtualMachineTemplate
      kubernetes.core.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachineInstanceTemplate
        name: "{{ template_name }}"
        namespace: "{{ namespace }}"
      register: vm_template

    - name: Fail if template not found
      fail:
        msg: "Template {{ template_name }} not found in namespace {{ namespace }}."
      when: vm_template.resources | length == 0

    - name: Create a VirtualMachine from the catalog template
      kubernetes.core.k8s:
        state: present
        definition: >
          {{
            vm_template.resources[0] | combine({
              "metadata": {
                "name": vm_name,
                "namespace": target_namespace
              }
            })
          }}
      register: create_vm

    - name: Wait for the VM to be ready
      kubernetes.core.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachineInstance
        name: "{{ vm_name }}"
        namespace: "{{ target_namespace }}"
      register: vmi
      retries: 60
      delay: 10
      until: >
        (vmi.resources[0].status.phase == "Running") and
        (vmi.resources[0].status.interfaces | default([]) | length > 0)

    - name: Print the IP address of the VM
      debug:
        msg: "The IP address of the virtual machine {{ vm_name }} is: {{ vmi.resources[0].status.interfaces[0].ipAddress }}"
